### ISSUE TITLE
Great to meet you

### ISSUE THREAD

**Issue by puttputt** [Daniil-Aleshechkin/tetris-rtos#1]
Hey Daniil,

Apologies for the intrusive PR but I couldn't figure out how to contact you.

We met at project day and I was really impressed with your project.

I know you have a role with iQmetrix at the moment (although things are a bit shaky there as you've described), and we are not explicitly hiring at the moment - but if its a good fit we'd make an exception.

Our tech stack is mostly web/typescript. Front-end apps in Angular, Svelte and React (our main app is currently an Angular/React hybrid as we migrate to React), back-end node.js on various AWS services.

My ask from you today is if I could get your contact information (send me an email [kyle@joinoffstreet.com](mailto:kyle@joinoffstreet.com)), or add me on [LinkedIn](https://www.linkedin.com/in/kylesmyth/) if it's easier. I'm decently connected in the SK-technology ecosystem so if there's a tech company in the province you want an intro to I can totally make that happen.

If you're interested in going down the full-stack web-dev path, we have an always open job posting to collect resume's: https://offstreet.bamboohr.com/careers/24

Good luck with finals, you're almost done!

**Comment by Daniil-Aleshechkin** [comment]
Thanks I've reached out!
